### PR TITLE
Increased maxBuffer size

### PR DESCRIPTION
**Pull request by rjwaring**

### CODE REVIEW

**Comment by TomSeldon** [comment]
:+1:

**Comment by jenkoian** [comment]
How come we've forked? Is this something we'd want to contribute back?

**Comment by rjwaring** [comment]
Yeah, it appears we're not the only ones having this trouble and it's a reasonably easy temporary fix for them to add. PR into the original master is https://github.com/davidrekow/closure-compiler-stream/pull/4

**Comment by jenkoian** [comment]
Cool - know you boys are slammed on MP but if you get chance may be nice to tidy that PR up a bit - seems there is a nicer way to do that, where we don't hard code values etc. Also, I'm not sure we should be making the whitespace changes.

**Comment by rjwaring** [comment]
The whitespace stuff is just where I've changed the indent because of the new parameter. Could probably do the numbers better though.

**Pull request merged**
